apigateway/pom.xml
frontend/pom.xml
pom.xml

Added sonar dependencies and tested locally with  `mvn clean verify sonar:sonar -Dsonar.login=xxxxxxxxxxxxxxxxxxxxxxxx`
**Reference**
Issues #ZMS-1064

Add sonar dependencies

---

frontend/__tests__/components/Calendar.spec.js
frontend/src/components/TheCalendar.vue

feat(ZMS-1350): show error message

---

frontend/src/components/AppointmentForm.vue
frontend/src/store/modules/api/actions.js

feat(ZMS-1350): added error handling

---

frontend/src/components/TheCalendar.vue

feat(ZMS-1350): fix error handling

---

frontend/src/translations/de/index.js

feat(ZMS-1335): fix test

---

frontend/src/components/AppointmentForm.vue

feat(ZMS-1219): remove duplicate requests

---

frontend/src/components/TheCalendar.vue

feat(ZMS-1219): fix displayed times

---

frontend/__tests__/components/Calendar.spec.js

feat(ZMS-1219): fix tests

---

frontend/src/components/CustomerInfo.vue

feat(ZMS-1493): adjust next button on mobile

---

frontend/__tests__/store/modules/formData/mutations.spec.js
frontend/src/store/modules/formData/mutations.js

feat(ZMS-1494): fix missing sub service

---

frontend/src/components/ServiceFinder.vue
frontend/src/store/actions.js
frontend/src/store/modules/formData/index.js
frontend/src/store/modules/formData/mutations.js
frontend/src/translations/de/index.js

Feature 1565 show error for max slot

---

frontend/src/store/modules/formData/mutations.js
frontend/src/translations/de/index.js

feat(ZMS-1565): remove test

---

frontend/__tests__/components/AppointmentForm.spec.js
frontend/__tests__/components/ServiceFinder.spec.js
frontend/src/components/ServiceFinder.vue
frontend/src/store/modules/formData/mutations.js

feat(ZMS-817): disable plus minus button

---

frontend/src/translations/de/index.js

Vor - und Nachname
**Reference**
Issues #1696

Quick Fix Vor - und Nachname

---

frontend/src/components/TheCalendar.vue
frontend/src/store/actions.js

feat(ZMS-815): fix preselecting provider

---

frontend/src/components/TheCalendar.vue

feat(ZMS-815): add logging

---

frontend/src/components/TheCalendar.vue

feat(ZMS-815): add more logging

---

frontend/src/components/TheCalendar.vue

Feature zms 815 provider priselect by rebooking

---

frontend/src/components/TheCalendar.vue

feat(ZMS-815): select provider

---

frontend/src/components/TheCalendar.vue

feat(ZMS-815): clean

---

frontend/src/components/TheCalendar.vue

feat(ZMS-815): add some logging

---

frontend/src/components/TheCalendar.vue

fat(ZMS-815): fix selecting provider

---

frontend/src/components/TheCalendar.vue

feat(ZMS-815): fix selecting provider

---

frontend/src/components/TheCalendar.vue
frontend/src/store/actions.js

feat(ZMS-815): fix

---

frontend/src/components/TheCalendar.vue

feat(ZMS-815): refactoring

---

frontend/src/components/TheCalendar.vue

feat(ZMS-815): fis preselecting provider tab

---

frontend/src/components/TheCalendar.vue

feat(ZMS-815): fix selecting provider tab

---

frontend/src/components/TheCalendar.vue

feat(ZMS-815): fix preselect provider

---

frontend/src/components/TheCalendar.vue

feat(ZMS-815): remove console logs

---

frontend/src/components/AppointmentForm.vue
frontend/src/components/InfoMessage.vue

Fix 1908 fix jumping on content

---

frontend/src/components/AppointmentForm.vue
frontend/src/components/TheCalendar.vue
frontend/src/translations/de/index.js

Fix 1270 vuetify language

---

frontend/src/components/TheCalendar.vue

fix(ZMS-1271): adjust weekdays

---

frontend/src/components/TheCalendar.vue

fix(ZMS-1313): adjust timeblock

---

frontend/src/components/ServiceFinder.vue

fix(ZMS-1268): fix aria label

---

frontend/src/translations/de/index.js

Bug 1956 - Satz geaendert

---

frontend/__tests__/components/CustomerInfo.spec.js
frontend/src/components/CustomerInfo.vue
frontend/src/store/actions.js
frontend/src/store/modules/api/actions.js
frontend/src/translations/de/index.js

Feature 1784 check if too many appointments with same mail

---

frontend/src/components/AppointmentForm.vue
frontend/src/translations/de/index.js

feat(ZMS-1784): refactoring

---

frontend/src/components/CustomerInfo.vue

ZMS-1955_disable_box_on_rebooking  into dev

---

frontend/src/components/ServiceFinder.vue
frontend/src/store/modules/formData/mutations.js

Feature zms 2357 max slots by provider

---

.github/workflows/api-gateway.yaml
.github/workflows/frontend.yaml
frontend/src/App.vue
frontend/src/components/NotFound.vue
frontend/src/store/actions.js
frontend/src/store/index.js
frontend/src/store/modules/api/actions.js
frontend/src/translations/de/index.js
frontend/src/translations/en/index.js

Add NotFound 404 page for incorrect services to location into dev

---

frontend/__tests__/components/AppointmentForm.spec.js
frontend/__tests__/store/modules/formData/mutations.spec.js
frontend/src/components/AppointmentForm.vue
frontend/src/components/ServiceFinder.vue
frontend/src/store/actions.js
frontend/src/store/modules/formData/mutations.js
frontend/src/store/mutations.js

Bugfix zms 2476 fix service combination

---

frontend/src/store/modules/formData/mutations.js

fix(ZMS-2476): fix displaying selected services

---

frontend/src/App.vue

fix too many appointment with same email

---

frontend/src/App.vue

fix loading apointment form

---

frontend/public/css/patternlab.css
frontend/src/components/NotFound.vue

Bug ZMS-2596 changed arrow direction

---

frontend/__tests__/components/CustomerInfo.spec.js
frontend/src/components/CustomerInfo.vue

Bug zms 1957 fix checkbox selection

---

frontend/src/components/AppointmentForm.vue
frontend/src/components/InfoMessage.vue
frontend/src/components/TheCalendar.vue
frontend/src/store/index.js

Feature zms 2699 display location info

---

frontend/__tests__/components/Calendar.spec.js
frontend/src/components/AppointmentForm.vue
frontend/src/components/TheCalendar.vue
frontend/src/store/modules/formData/index.js
frontend/src/store/modules/formData/mutations.js

Bugfix zms 2745 show all locations

---

frontend/__tests__/components/AppointmentForm.spec.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/AppointmentForm.vue

Bugfix zms 1821 fix button text

---

README.md

docs(ZMS): Update README.md

---

apigateway/pom.xml
frontend/src/components/AppointmentForm.vue

dev into feature-MPDZBS-877-zmscitizenapi

---

frontend/src/App.vue
frontend/src/components/AppointmentForm.vue
frontend/src/store/actions.js
frontend/src/store/modules/api/actions.js
frontend/src/store/mutations.js
frontend/src/translations/de/index.js
frontend/src/translations/en/index.js

feat(ZMSKVR-371): set maintenance mode when offices and services not reachable

---

frontend/__tests__/components/Calendar.spec.js
frontend/src/components/TheCalendar.vue

Feature zmskvr 309 disable provider by services

---

apigateway/pom.xml
renovate.json

next into main
